#!/bin/bash
set -eu


PRIVATE_KEY_FILE=$1

function printInputError {
  echo "Usage: $0 KEYFILE [FILE]…" >&2
  exit 1
}
if [ "$#" -le 1 ]; then
  printInputError
fi
for TARGET in "${@:1}"; do
  if ! [ -f "${TARGET}" ]; then
    printInputError
  fi
done

for TARGET in "${@:2}"; do
  openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sign ${PRIVATE_KEY_FILE} ${TARGET} | openssl base64 -out ${TARGET}.signature
done
