name: Test
on:
  push:
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+.*", "trigger-push"]
  pull_request:
  schedule:
    # Weekly full matrix run on Mondays at 04:00 UTC.
    - cron: "0 4 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  smoke-test:
    name: Smoke test (${{ matrix.platform }})
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    strategy:
      matrix:
        go-version: [ '1.26' ]
        platform: [ ubuntu-24.04, windows-2025 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Run CI
        uses: ./.github/actions/run-tests
        with:
          go-version: ${{ matrix.go-version }}

  full-test:
    name: Full test (${{ matrix.platform }})
    if: github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/master')
    strategy:
      matrix:
        go-version: [ '1.26' ]
        # Note: 'macos-26' for arm does not yet work
        platform: [ ubuntu-22.04, ubuntu-24.04, macos-15-intel, windows-2025 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Run CI
        uses: ./.github/actions/run-tests
        with:
          go-version: ${{ matrix.go-version }}
